# Generated by Django 4.0.2 on 2022-02-06 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_details',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 13, 4, 26, 451850)),
        ),
    ]
