# Generated by Django 4.0.2 on 2022-02-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4)),
                ('operatorName', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
